### ISSUE TITLE
Windows-friendly setup script

### ISSUE THREAD

**Issue by ghost** [X0R0X/cli-torrent-dl#21]
I don't know a damn thing about powershell, but it doesn't seem too difficult. I'll have to research this more.

**Comment by X0R0X** [comment]
Would be nice. BUT the proble isnt powershell, problem is ncurses, it crashes due to winterm... :X I don't have the nerves to debug it on windows at the moment.

**Comment by X0R0X** [comment]
On the other hand... I should (maybe I'am gonna) ...

**Comment by Mr-ROPer** [comment]
Maybe we should eventually switch to [unicurses](https://pypi.org/project/UniCurses/). It's by no means a drop-in replacement, but its syntax is closer to original ncurses. Since I have a lot of C experience, I don't think this would take me _very_ long. It's definitely not a priority, though.
