### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by Mr-ROPer** [X0R0X/cli-torrent-dl#22]
Add support for copying magnets to clipboard instead of opening torrent client. We could also just add a hotkey for copying instead of overriding the opening functionality.

**Comment by X0R0X** [comment]
#571d78e Done mate ;) Btw lemme know, would be great to connect again. I didnt have much time for hobby projects last year or so :/

**Comment by Mr-ROPer** [comment]
That’d be nice. I can’t get into Telegram anymore, but I’d love to catch up. Cloudflare has broken many engines.
