### ISSUE TITLE
pkg-resources==0.0.0 prevents installation

### ISSUE THREAD

**Issue by repkid** [X0R0X/cli-torrent-dl#25]
I'm on linux and the line:
`pkg-resources==0.0.0 in requirements.txt`

prevents the installation from completing with the following error:
```
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0
```
installation worked fine when that line is removed from requirements.txt

**Comment by silkyland** [comment]
Just remove this line from requirements.txt

**Comment by repkid** [comment]
neato, now it just needs to be merged

**Comment by X0R0X** [comment]
Dunno why that was there, bah ^^ It was surely removed loong ago.
