### ISSUE TITLE
Nothing happens when aria2c is set as torrent client

### ISSUE THREAD

**Issue by carlak1701** [X0R0X/cli-torrent-dl#28]
I edited the config file as follows:

"torrent_client_cmd": "aria2c ~/Downloads --follow-torrent=mem %s"

When I hit enter on the relevant file within tordl, nothing happens.

**Comment by ElonSatoshi** [comment]
Check `pidof aria2c` and `htop`

**Comment by X0R0X** [comment]
Ok, got it. 

 "torrent_client_cmd": "aria2c -d ~/Downloads --seed-time=0 %s"

cheers mate.
