### ISSUE TITLE
Error while searching

### ISSUE THREAD

**Issue by divyagar** [X0R0X/cli-torrent-dl#29]
When I am searching something, for eg. `tordl debian 8`, sometimes it is working but sometimes it is showing following error:
![Screenshot from 2021-08-09 16-28-19](https://user-images.githubusercontent.com/42246254/128696651-362d2658-9f32-4c98-bc4b-79b72d3f2db9.png)

**Comment by Mr-ROPer** [comment]
Yeah, sometimes DNS and SSL errors occur, and we don't have any mechanism to handle them yet. I noticed this a while ago, and didn't get around to fixing it. The main dev seems to have disappeared, and I don't have write access, so I'm just going to maintain my own fork. I'll post a link once I publish a fix, but feel free to check my profile in the meantime.

**Comment by X0R0X** [comment]
d4ng3r1n0 -  thx for ingenious answer :) Should be fixed now together with all kind of HTTP errors.

**Comment by d4ng3r1n0** [comment]
@X0R0X That's what we are for, everything that is to bring to the community is welcome
