### ISSUE TITLE
Introduce headless selenium based scraping

### ISSUE THREAD

**Issue by X0R0X** [X0R0X/cli-torrent-dl#33]
So we are not limited to non-js sites only.

**Comment by Mr-ROPer** [comment]
There are some good stealth setups that can get past Cloudflare and such. I have had good luck with them in testing.

**Comment by X0R0X** [comment]
Could you create some working (example) scraper for, for example https://bt4g.org/ ? Cheers BTW :)

**Comment by Mr-ROPer** [comment]
Once I’m done with exams, I should have something working

**Comment by X0R0X** [comment]
cool, mate
