### ISSUE TITLE
virtualenv

### ISSUE THREAD

**Issue by gingamann** [X0R0X/cli-torrent-dl#37]
As a requisite, need to have installed python3 & python3-virtualenv. 

Took a bit for me to get there, but easier to have it as an additional requisite....   i.e.

Prerequisites

    Python 3.8+
    python3-virtualenv

**Comment by X0R0X** [comment]
Added :) , thanks and sorry for your lost time

**Comment by manicExpressive** [comment]
I was installing on Ubuntu for the first time and this helped me realize I needed to do a quick `sudo apt install python3-virtualenv` to get my installation moving, thanks!
