### ISSUE TITLE
Workaround: adding selected torrent to Transmission

### ISSUE THREAD

**Issue by neilbaldwin** [X0R0X/cli-torrent-dl#40]
I struggled for ages trying to add torrents to my Transmission client from the tordl browser window but I managed a workaround:

In “func.py” change the  `run_torrent_clien()` function to:

`def run_torrent_client(magnet_url):
  cmd = (cfg.TORRENT_CLIENT_CMD + " '" + magnet_url + "'")
  subprocess.Popen(
    cmd,
    stderr=subprocess.DEVNULL,
    stdout=subprocess.DEVNULL,
    shell=True
  )
`
So combining the command and parameters into a single string and using the ‘shell=True’ option for subprocess.

And in your config file:

`"torrent_client_cmd": "transmission-remote --auth USER:PASSWORD --add" `

Works perfectly now 👍🏻

**Comment by neilbaldwin** [comment]
Posting here in case anyone else was having similar issues.

Thanks for tordl, it’s superb 🙏🏻

**Comment by X0R0X** [comment]
Glad You like it :),
You actually need tthis to your config file : "torrent_client_cmd": "transmission-remote --auth USER:PASSWORD --add %s"
- %s at the end, it's substituded.

cheers

**Comment by neilbaldwin** [comment]
It wasn't working for me using "%s* in the command setting string, I would get an error saying "filename too long". That's why I wododied the code and with that modification you don't need "%s" as the code already appends magnet_url parameter. Could be a quirk of my system, I'm running on a headless Raspberry Pi 5  (Bookworm, 64) and Python 3.11.2

**Comment by X0R0X** [comment]
Ah, I see, Ok, thx
